[character]
success_symbol = "[](#1cd404)"
error_symbol = "[](#9d0003)"
vicmd_symbol = "[](#1cd404)"

[aws]
symbol = " "
format = "[$symbol$profile(\\($region\\))]($style) "

[directory]
format = "[$path]($style) "
style = "bold italic #7096ff"

[git_branch]
symbol = ""
format = "[$symbol $branch]($style) "
style = "bold italic #eb5c1b"

[git_status]
format = "[$all_status$ahead_behind](purple)"
ahead = " "
behind = " "
conflicted = " "
deleted = " "
diverged = " "
modified = " "
renamed = "ﳟ "
staged = " "
stashed = " "
untracked = " "

[golang]
symbol = " "
format = "[$symbol$version](#6fcce4) "

[kubernetes]
disabled = true

[nodejs]
symbol = " "
format = "[$symbol$version](#ffd700) "

[package]
format = "[$symbol$version](#ab764d) "

[rust]
format = "[$symbol$version](#e34116) "

[java]
format = "[$symbol($version )]($style)"

[scala]
symbol = " "
format = "[$symbol($version )]($style)"

[python]
format = "[$symbol($version )]($style)"

[username]
disabled = true

[custom.git_remote]
command = "git remote get-url origin 2>/dev/null | sed 's|.*://||;s|.*@||;s|/.*||;s|:.*||'"
when = "git rev-parse --git-dir 2>/dev/null"
format = "[$output]($style) "
style = "bold #eb5c1b"

