[character]
symbol = ""
error_symbol = ""
style_success = "#1cd404"
style_failure = "#9d0003"
use_symbol_for_status = true
vicmd_symbol = ""

[aws]
symbol = " "

[directory]
style = "bold italic #7096ff"

[git_branch]
symbol = " "
style = "bold italic #eb5c1b"

[git_status]
style = "purple"
prefix = ""
suffix = ""
ahead = " "
behind = " "
conflicted = " "
deleted = " "
diverged = " "
modified = " "
renamed = "ﳟ "
staged = " "
stashed = " "
untracked = " "

[golang]
symbol = " "
style = "#6fcce4"

[kubernetes]
disabled = true

[nodejs]
symbol = " "
style = "#0d5e00"

[package]
style = "#ab764d"

[rust]
style = "#e34116"
