[character]
success_symbol = "[](#1cd404)"
error_symbol = "[](#9d0003)"
vicmd_symbol = "[](#1cd404)"

[aws]
symbol = " "
format = "[$symbol$profile(\\($region\\))]($style) "

[directory]
format = "[$path](bold italic #7096ff) "

[git_branch]
symbol = ""
format = "[$symbol $branch](bold italic #eb5c1b) "

[git_status]
format = "[$all_status$ahead_behind](purple)"
ahead = " "
behind = " "
conflicted = " "
deleted = " "
diverged = " "
modified = " "
renamed = "ﳟ "
staged = " "
stashed = " "
untracked = " "

[golang]
symbol = " "
format = "[$symbol$version](#6fcce4) "

[kubernetes]
disabled = true

[nodejs]
symbol = " "
format = "[$symbol$version](#f7de42) "

[package]
format = "[$symbol$version](#ab764d) "

[rust]
format = "[$symbol$version](#e34116) "
