alias cat='pygmentize -O style=monokai -f console256 -g'
alias fixopenwith='/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user'
alias json='jq "."'
alias xml='xmllint --format -'
alias hs='history | grep'
alias nls='npm list -g --depth=0'
alias ni='npm install'
alias nis='npm install --save'
alias nisd='npm install --save-dev'
alias bls='brew list'
alias v='mvim'
alias bo='brew outdated'
alias bucp='brew upgrade && brew cleanup && brew prune'
alias chrome-dev='open -a /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --args --disable-web-security -–allow-file-access-from-files'
alias appstore='find /Applications -path "*Contents/_MASReceipt/receipt" -maxdepth 4 -print |\sed "s#.app/Contents/_MASReceipt/receipt#.app#g; s#/Applications/##"'
alias gn='geeknote'
alias gti='git'
alias get='git'
alias glom='git pull origin master'
alias gpom='git push origin master'
